stages:
  - deploy

deploy:
  stage: deploy
  image: ubuntu:latest
  script:
    - apt-get update && apt-get install -y openssh-client
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh -o StrictHostKeyChecking=no -p $SSH_PORT $SSH_USER@$SSH_HOST "cd /var/www/myapp && git pull origin main && npm install && pm2 restart myapp"
  environment:
    name: production
  only:
    - main
