name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Configure Kubernetes
        uses: azure/kubernetes-configure@v1
        with:
          creds: ${{ secrets.KUBE_CONFIG_DATA }}
          namespace: myapp
          cluster-name: my-cluster
          config-filepath: ./kubeconfig.yaml

      - name: Deploy to Kubernetes
        uses: appleboy/kubectl-action@v1
        with:
          command: apply
          args: -f ./kubernetes/deployment.yaml
          kubernetes-server-url: ${{ secrets.KUBE_SERVER }}
          kubernetes-token: ${{ secrets.KUBE_TOKEN }}
